linters-settings:
  wsl:
    allow-cuddle-declarations: true
  funlen:
    lines: 80
    statements: 60

linters:
  # you can see what is disabled with: golangci-lint linters
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

issues:
  exclude-rules:
    - linters: ["gocritic"]
      text: "ifElseChain:"
    # test files can have globals
    - linters: ["gochecknoglobals"]
      path: _test.go
